import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          storageKey="product-in-bio-theme"
          defaultTheme="dark"
          themes={["light", "dark"]}
        >
          {children}
          <Toaster
            position="bottom-center"
            closeButton={true}
            richColors={true}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
